# docker-compose.yaml
version: '3'

services:
  web:
    build: '.'
    ports:
      - '8000:8000'
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1197sebas
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql